Almanac Documentation

You will find all the details about the Almanac format and command line
tool right here.

* Table of Contents
- [[#Installation][Installation]]
  - [[#binary-release][Binary Release]]
  - [[#build-from-source][Build from source]]
  - [[#in-progress-package-managers][Package Managers]]
- [[./Foramt.md][Format]]
- [[./Usage.md][Usage]]

* Installation
** Binary Release
For Windows, Mac OS or Linux, you can download a binary release here.

** Build from source
To build Almanac from source, make sure you have =go= installed with
version >= 1.18.1.

First clone this repo.

#+begin_src shell
git clone https://github.com/ParthTri/Almanac.git
#+end_src

Next =cd= in to the directory.

#+begin_src shell
cd Almanac
#+end_src

Finally run the build script:

#+begin_src shell
./build.sh
#+end_src

This will create a binary in the =bin= directory, from there you should
move it to somewhere on your =$PATH=.

** IN PROGRESS Package Managers
This is a work in progress feature, where you should be able to add it
with your choice of package manager.

Intended Support:
- AUR
- Homebrew
- Scoop (Windows)
- Debian
- Void Linux
- Nix
